### ISSUE TITLE
Feature Suggestion: Axarva's XMonad Configuration

### ISSUE THREAD

**Issue by psygo** [archcraft-os/archcraft-xmonad#4]
First of all, thank you very much for the Archcraft project. I've been using the i3 configuration for about 2 weeks now and it works like a charm &mdash; I've also sent a donation to thank you. However, XMonad used to be my main WM and I would like to go back to it at some point. And that's when I found Axarva's XMonad config, which blew my mind completely...

[Here is Axarva's configuration](https://github.com/Axarva/dotfiles-2.0). Since it is so popular, I think it would bring even more people to Archcraft. His/her configuration is kind of [famous on r/unixporn](https://www.reddit.com/r/unixporn/comments/knv0r4/xmonad_youhavenoideawhatspossible_edition/).

I don't really know why, but installing it directly, from the repo, didn't work entirely, a lot of things didn't work as expected.

I don't know if everything in that configuration will please most people though, but the beauty of the floating dissociated panes is really appealing to me.

**Comment by adi1090x** [comment]
I'll create my own in future.
